/* =============================================================================
   Cadence — DataSource layer (live)
   -----------------------------------------------------------------------------
   Static JSON generated by scripts/fetch_data.py:
     /data/catalog.json  — every Nordnet share / fund / ETF (search index)
     /data/a/<id>.json   — timing analytics (weekday/hour/month edges, day×hour
                           matrix, earnings, recommendation) per timeframe
     /data/s/<n>.json    — 256 detail shards for ALL instruments (id % 256)
     /data/meta.json     — asOf + counts
   ============================================================================ */

const SHARDS = 256;

let _catalog = null;
let _catalogPromise = null;
const _aCache = new Map();
const _shardCache = new Map();

async function getJSON(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return res.json();
}

export async function loadMeta() {
  try { return await getJSON('/data/meta.json'); } catch { return null; }
}

export function loadCatalog() {
  if (!_catalogPromise) {
    _catalogPromise = getJSON('/data/catalog.json').then(c => { _catalog = c; return c; });
  }
  return _catalogPromise;
}

export async function fetchAnalytics(id) {
  if (_aCache.has(id)) return _aCache.get(id);
  try {
    const a = await getJSON(`/data/a/${id}.json`);
    _aCache.set(id, a);
    return a;
  } catch {
    _aCache.set(id, null);
    return null;
  }
}

export async function fetchDetail(id) {
  if (id === 'OSEBX') return null;
  const shard = Number(id) % SHARDS;
  let sh = _shardCache.get(shard);
  if (!sh) {
    sh = await getJSON(`/data/s/${shard}.json`);
    _shardCache.set(shard, sh);
  }
  return sh[String(id)] || null;
}

/* ---- catalog search: relevance, then Nordnet owner count ------------------ */
export function searchCatalog(catalog, q, limit = 50) {
  const s = q.trim().toLowerCase();
  if (!s) {
    return [...catalog].sort((a, b) => (b.hasA - a.hasA) || (b.owners || 0) - (a.owners || 0)).slice(0, limit);
  }
  const scored = [];
  for (const c of catalog) {
    const sym = (c.sym || '').toLowerCase();
    const name = (c.name || '').toLowerCase();
    let score = -1;
    if (sym === s) score = 100;
    else if (sym.startsWith(s)) score = 80;
    else if (name.startsWith(s)) score = 60;
    else if (name.includes(s)) score = 40;
    else if (sym.includes(s)) score = 30;
    else if ((c.isin || '').toLowerCase() === s) score = 90;
    if (score >= 0) scored.push([score, c]);
  }
  scored.sort((a, b) => (b[0] - a[0]) || ((b[1].owners || 0) - (a[1].owners || 0)));
  return scored.slice(0, limit).map(x => x[1]);
}

/* ---- shape one (analytics, timeframe) into the view the UI renders -------- */
export function buildView(a, tf) {
  if (!a) return null;
  const t = a.tf[tf] || a.tf[Object.keys(a.tf)[0]];
  if (!t) return null;
  const rec = t.recommendation;
  const earnings = a.earnings;
  const bestDay = t.weekday.reduce((x, y) => (y.edge > x.edge ? y : x));
  const bestMonth = t.month.reduce((x, y) => (y.edge > x.edge ? y : x));
  const bestHour = t.hour ? t.hour.reduce((x, y) => (y.edge > x.edge ? y : x)) : null;
  const m3 = a.momentum.m3;

  const headline = rec.earningsSoon ? 'Hold off — earnings ahead'
    : rec.verdict === 'BUY' ? 'Timing favours accumulating'
    : rec.verdict === 'SELL' ? 'Timing favours trimming'
    : 'No decisive timing edge';

  const rationale = [];
  if (rec.bestWindow && rec.bestWindow.hour != null) {
    rationale.push(`Strongest edge clusters on ${rec.bestWindow.day} around ${rec.bestWindow.hour}:00–${+rec.bestWindow.hour + 1}:00 (edge ${rec.bestWindow.edge}/100).`);
  } else if (rec.bestWindow) {
    rationale.push(`Strongest edge clusters on ${rec.bestWindow.day} (edge ${rec.bestWindow.edge}/100).`);
  }
  rationale.push(`${bestDay.key} is the most favourable weekday; ${bestMonth.key} leads the seasonal pattern.`);
  rationale.push(
    rec.verdict === 'BUY'
      ? `Momentum is positive (${m3 >= 0 ? '+' : ''}${m3}% over 3 months) and aligns with favourable session patterns.`
      : rec.verdict === 'SELL'
        ? `Momentum is negative (${m3}% over 3 months) and the volatility-adjusted edge skews weak.`
        : 'Signals are mixed across the window — no decisive timing advantage right now.'
  );
  if (earnings && earnings.kind === 'stock' && earnings.next) {
    const e = earnings.next;
    if (rec.earningsSoon) {
      rationale.unshift(`${e.label} report in ${e.daysUntil} day${e.daysUntil === 1 ? '' : 's'} (${e.date}) — volatility spikes around results; most edges break down through the print.`);
    } else if (earnings.reportDayMove != null) {
      rationale.push(`Next report ${e.label} on ${e.date} (in ${e.daysUntil} days). Report-day moves average ±${earnings.reportDayMove}%, with elevated volatility for ~${earnings.postElevatedSessions} sessions after.`);
    } else {
      rationale.push(`Next report ${e.label} on ${e.date} (in ${e.daysUntil} days).`);
    }
  } else if (earnings && earnings.kind === 'index' && earnings.peakMonths?.length) {
    rationale.push(`Reporting season peaks in ${earnings.peakMonths.join(', ')} — expect broader swings as constituents report.`);
  }

  return {
    instrument: a.instrument,
    asOf: a.asOf,
    timeframe: tf,
    sampleSize: t.sampleSize,
    intradayDays: t.intradayDays,
    weekday: t.weekday,
    hour: t.hour,
    month: t.month,
    matrix: t.matrix,
    earnings,
    momentum: a.momentum,
    daysAxis: a.daysAxis,
    hoursAxis: a.hoursAxis,
    monthsAxis: a.monthsAxis,
    bestDay, bestMonth, bestHour,
    recommendation: { ...rec, headline, rationale },
  };
}
